export const ActionTypes = {
  SET_ACCOUNT_DATA: "SET_ACCOUNT_DATA",
  SET_DETAIL_COURSES_USER: "SET_DETAIL_COURSES_USER",
  SET_COMMENTS: "SET_COMMENTS",
  SET_DETAIL_SPESIALISASI_USER: "SET_DETAIL_SPESIALISASI_USER",
  REMOVE_SELECTED_SPESIALISASI: "REMOVE_SELECTED_SPESIALISASI",
  REMOVE_SELECTED_COURSES: "REMOVE_SELECTED_COURSES",
  SET_QUIZ_SCORE: "SET_QUIZ_SCORE",
  REMOVE_SELECTED_COMMENTS: "REMOVE_SELECTED_COMMENTS",
};
